### ISSUE TITLE
Dropbox-DD-Images of data_leakage_cases of "Lab 0" PPT are broken.

### ISSUE THREAD

**Issue by elaOnMars** [frankwxu/digital-forensics-lab#8]
The links within the PPT slide of "Lab 0" don't provide valid 7z images. The link to the original data files of the NIST are hidden below an image with the link to some dropbox files. The original case study files should be used instead:
+ https://cfreds-archive.nist.gov/data_leakage_case/images/pc/cfreds_2015_data_leakage_pc.7z.001
+ https://cfreds-archive.nist.gov/data_leakage_case/images/pc/cfreds_2015_data_leakage_pc.7z.002
+ https://cfreds-archive.nist.gov/data_leakage_case/images/pc/cfreds_2015_data_leakage_pc.7z.003

Please update your PPT files. Thank you.

Here is the image creation failure of your files:
`
└─$ ls -l       
insgesamt 6291480
-rw-r--r-- 1 kali kali 2147483648 23. Feb 15:32 cfreds_2015_data_leakage_pc.7z.001
-rw-r--r-- 1 kali kali 2147483648 23. Feb 15:58 cfreds_2015_data_leakage_pc.7z.002
-rw-r--r-- 1 kali kali 2147483648 23. Feb 16:28 cfreds_2015_data_leakage_pc.7z.003

└─$ 7z e cfreds_2015_data_leakage_pc.7z.001

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=de_DE.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (306A9),ASM,AES-NI)

Scanning the drive for archives:
1 file, 2147483648 bytes (2048 MiB)

Extracting archive: cfreds_2015_data_leakage_pc.7z.001
ERROR: cfreds_2015_data_leakage_pc.7z.001
cfreds_2015_data_leakage_pc.7z
Open ERROR: Can not open the file as [7z] archive

ERRORS:
Headers Error
WARNINGS:
There are data after the end of archive
    
Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
`

**Comment by frankwxu** [comment]
Links are fixed. Please try again.

**Comment by elaOnMars** [comment]
I'm using LibreOffice. Can't open the PPT because of some filter. The files are too small for being a PPTX.
Please check your slides or add the old ones with a hint. Thanks in advance.

**Comment by elaOnMars** [comment]
Looks good. Thank you.
